spring.application.name=StockApplication

# URL de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/stock
spring.datasource.username=root
spring.datasource.password=2483

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect